name    'herculesteam-augeasproviders_syslog'
version '1.0.0'
source 'git://github.com/hercules-team/augeasproviders_syslog'
author 'Dominic Cleal, Raphael Pinson'
license 'Apache 2.0'
summary 'Augeas-based syslog type and providers for Puppet'
description 'This module provides type/providers for syslog using the Augeas configuration API library.'
project_page 'http://augeasproviders.com'
